### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by veksha** [ildarkhasanshin/cuda_scratches#19]
i compiled one of my scratches and binary file appeared in scratches dir.
now i get error when using `Scratches: List` command.

```python
Traceback (most recent call last):
  File "F:\MySSDPrograms\cudatext\py\cuda_scratches\__init__.py", line 103, in list
    items, items_ = get_files_list(self)
  File "F:\MySSDPrograms\cudatext\py\cuda_scratches\__init__.py", line 30, in get_files_list
    line_count = sum(1 for line in open(item, 'r', encoding='utf-8'))
  File "F:\MySSDPrograms\cudatext\py\cuda_scratches\__init__.py", line 30, in <genexpr>
    line_count = sum(1 for line in open(item, 'r', encoding='utf-8'))
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
ERROR: Exception in CudaText for list: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_scratches/commit/0778d090108d1597e5a462bbfc07eadbf4bdd216
